--- #YAML:1.0
name:               Perl-Critic-Policy-CodeLayout-ProhibitSpaceIndentation
version:            1.01
abstract:           Use tabs instead of spaces for indentation.
author:
    - Infoxchange Australia <devs@infoxchange.net.au>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
